server:
  port: 3030




spring:
  application:
    name: Book-Review-Service



  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book
    username: postgres
    password: 123
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect